### ISSUE TITLE
Contact information disappears when all Experience section Accordions are closed

### ISSUE THREAD

**Issue by mujtabacodes** [mujtabacodes/Portfolio-Next#2]
## Issue Summary

When all sections of experience are close then in footer contact information disappear

## Steps to Reproduce

1. Visit website https://mujtabacodes.com
2. Clicked on contact me buttom or scroll down till end
3. Then move up to experience section
4. Close all experience section and then view footer again

## Actual Results

![image](https://github.com/mujtabacodes/Portfolio-Next/assets/89851078/0be9836e-897b-40c8-95d1-232aee0fdeb3)

## Expected Results

![image](https://github.com/mujtabacodes/Portfolio-Next/assets/89851078/5399d2e9-fcbb-4baf-8823-2911a1edd006)

**Comment by cpwallah** [comment]
hi @mujtabacodes i have made pr you can see it ,made changes in social.tsx and in contact-us.tsx . everything is working fine that glitch got removed
